// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package subscription_storage

import ()

type Subscription struct {
	ID         int64 `json:"id"`
	UserID     int64 `json:"user_id"`
	ScheduleID int64 `json:"schedule_id"`
}
