// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package schedule_storage

import ()

type Schedule struct {
	ID         int64  `json:"id"`
	ActivityID int64  `json:"activity_id"`
	Datetime   string `json:"datetime"`
	Trainer    string `json:"trainer"`
	Activity   string `json:"activity"`
	PreEntry   bool   `json:"pre_entry"`
	BeginDate  string `json:"begin_date"`
}
